sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov

deploy:
  provider: opsworks
  access-key-id:
    secure: A53slkfZLar5POSBVdoWnnh5m0Mtv7k6gaST+PxihscSJCDkNkw19/MvfHil2YrNP9KrErEuwKdg8csOmjJ12HpUkv5n1RQOcE6d3LVOxOGB60PIxitvGrPmN3mIFf/aE02TQf1Z/0fPAJXEgEu6AZiA1uPqUKi9HTFUUIKnr7IvqblWtpXDURxWyt9RStjsqhKzxIhvi7Qf4IQ6+gI6kZ9xnNmqm3P5Rrt3505YO2tlkEWHVGW7IkS+FGPz8wXoG3T6YJCgFKEvSGIFl4sudyRodQpeIEvyNJ5yKezs53G9LvrNNyTRbu3NpmprFErPJSXtKyhDbEYFiieTpyJiSoITYwsfhbHa00ceYwBy7P4I97lug0cKyTh8j0nNkP+1wyxFHXay3RgAL7fRNDgW1dgcg+D4WJwfumU/N/BpdD/TNJ5GqRFJ8PKoj41lNoXruLL7hpdkdlHOLpP4U3ciiNNjfEUM1IBEM79XN5m1cJCFMfGH7tWmg0TDMeM+P1CNyHrCjg3MqL703fdJnTNOUwWvcaRcwOR+sKm0qbwGDWRp3S76WYimmbQGQ5LhjxFsD4qr7s0wZxvdjHyi95r+oHnGdKfSp1UYRSJTJFPKe6wSZmuDrofboVJDSd27m9HoNYMTrmJiNKw4AVPhfy/jz1hUrOGK8Q6T6JjoapzbDtk=
  secret-access-key:
    secure: OVH0p1yq1DI/9fWPveN3NqdTww1SBB4GBixwZ3Q2vl/CP9hC3J+xAFrLkuouwtxcDPGqyYo3cEm2lOoD66JgHEg3jpF5lbyT2mOi5gbMFyyfPOfTGa2YgkwCWS4nlDViqJCUs/0Uz7sPfkQphuYDdXhQ/XE3ifsOjaCzuXNhsxnwWf8j1TAcBubncWTk/TMxGbzWtn7fJ/+fNZ+8mdz+DvSDaesd/b3NA4nBQfq5ZwmL2SpGsLjUn43gJCmQECHtXuX0pUvmG59FEeiK87wcAIzDHzwMMKzLOZo/6OVCCRXnks3TSQN951Yqio6uDoOX8mCVV7nzwjgIglCgRyk0c8r60fX3MpYEUuhbR/jW4QbJ6sCnhpWg3oOGUhp4Hde5fqL9RZkDQZ0ooldNqKIgunmDfX0CdTkhG2FOT4fOjOV7lfPfUdP/HzmJrfqVMHLBdP0wNTeCnajWggZqKCYZ1bR05nh6ucqfblx/3zBcPMH5aEDrInEeDW50KI4KbOTrSCblwXJpKJory28xk2HHssjB5pu0qS6KnqgJt6fw5YehY+AtHA5ityvMNYFrhUYRa1EaqfQyFVM1lkDsBmHvmlEI3Nf+9TBJPivmgI9EsunCbgYo9XqRvAr1vyQprE36iUMMny3+vpZmyu3dTGncN8+6LMoeeI2D9vUtQ5ZilIQ=
  app-id: 5e2431e8-ab54-4424-a333-7573f8c7390d
  on: 
    branch: master
